---
- hosts: all
  remote_user: vagrant 
  become: yes

  roles:
    - ssh-access
    - 3cx-setup
    - devsec.hardening.ssh_hardening


  tasks:
  - name: HOW TO CONFIGURE & SETUP?
    debug:
      msg: "TO INSTALL and SETUP run `sudo apt install 3cxpbx`"
