---
- hosts: all
  remote_user: vagrant 
  become: yes

  roles:
    - ssh-access
    - 3cx-setup
    - devsec.hardening.ssh_hardening


  tasks:
  - name: HOW TO CONFIGURE & SETUP?
    debug:
      msg: "Access configuration wizard through a browser http://{{ ansible_default_ipv4.address }}:5015"
