- name: add {{ user }} user to sudoers
  user:
    name: "{{ user }}"
    group: sudo
    create_home: yes
    append: yes
    shell: /bin/bash

- name: allow {{ user }} to sudo
  lineinfile:
    path: /etc/sudoers
    line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
    create: yes

- name: grant access to {{ user }} using current user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
