---
- name: install dependencies
  apt:
    name: 
      - net-tools
      - dphys-swapfile
      - fail2ban
      - unattended-upgrades
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
      - debconf
      - debconf-utils
    update_cache: yes
    state: latest

- name: whitelist fail2ban
  lineinfile:
    path: /etc/fail2ban/jail.conf
    regexp: '^#ignoreip'
    line: 'ignoreip = {{ fail2ban_whitelist }}'
    backup: yes
  notify: restart fail2ban
  when: fail2ban_whitelist

- name: set swappiness to 10 when less than 10% memory left
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: yes

- name: set/increase cache pressure to 50
  sysctl:
    name: vm.vfs_cache_pressure
    value: '50'
    state: present
    reload: yes

- name: add 3cx signing key
  apt_key:
    url: http://downloads-global.3cx.com/downloads/3cxpbx/public.key
    state: present

- name: add 3cx repo
  apt_repository:
    repo: deb http://downloads-global.3cx.com/downloads/debian {{ ansible_distribution_release }} main
    state: present

- name: accept agreement
  debconf:
    name: 3cxpbx
    question: "3cxpbx/eula"
    value: 'true'
    vtype: select

- name: install 3cx
  apt:
    update_cache: yes
