---
- name: install dependencies
  apt:
    name: 
      - net-tools
      - dphys-swapfile
      - fail2ban
      - unattended-upgrades
    update_cache: yes
    state: latest

- name: set swappiness to 10 when less than 10% memory left
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: yes

- name: set/increase cache pressure to 50
  sysctl:
    name: vm.vfs_cache_pressure
    value: '50'
    state: present
    reload: yes

- name: add 3cx signing key
  apt_key:
    url: http://downloads-global.3cx.com/downloads/3cxpbx/public.key
    state: present

- name: add 3cx repo
  apt_repository:
    repo: deb http://downloads-global.3cx.com/downloads/debian {{ ansible_lsb.codename }} main
    state: present

- name: update cache
  apt:
    update_cache: yes
